Create new pipeline hookin, readd mocha reporter, moved out old cypre…
DFE-Digital/find-information-about-academies-and-trusts pull request #522
Opened 2024-09-27 13:06 UTC by CMurrell148

…ss folder

_Add a brief description of the purpose and contents of the pull request_

## Changes

_Add a summary of the changes in this pull request_

## Screenshots of UI changes

### Before

### After

## Checklist

- [ ] Pull request attached to the appropriate user story in Azure DevOps
- [ ] ADR decision log updated (if needed)
- [ ] Release notes added to CHANGELOG.md
- [ ] Testing complete - all manual and automated tests pass

2024-09-30 16:54 UTC, dynamictulip submitted a review, later dismissed
LGTM

2024-10-01 10:19 UTC, dynamictulip approved these changes

2024-10-01 11:07 UTC, DrizzlyOwl requested changes
There looks to be a regression by way of the removal of the OWASP ZAP Workflow `test-security.yml`. Could this please be reinstated, or a justification of it's removal included in the proposed change notes.

2024-10-01 11:12 UTC, DrizzlyOwl approved these changes
Approved on the proviso that OWASP ZAP will be reintroduced soon

2024-10-01 11:13 UTC, merged