Rename anti forgery cookie
DFE-Digital/find-information-about-academies-and-trusts pull request #575
Opened 2024-10-24 14:06 UTC by nwarms

[User Story 185649](https://dfe-gov-uk.visualstudio.com/Academies-and-Free-Schools-SIP/_workitems/edit/185649): Tech debt: make the anti forgery cookie name static

Rename the anti forgery cookie so it has a static name.

## Changes

- change the name of the anti forgery cookie on startup
- Update the automation tests to detect the correct cookie
- Update the cookie page so the correct cookie name is listed
- Update the delete method as the user auth app insights cookie name was incorrect and being persisted after declining cookies.

## Screenshots of UI changes

### Before
![image](https://github.com/user-attachments/assets/7cba3f01-db4d-4c7e-8f40-91a7712a0cee)

### After
![image](https://github.com/user-attachments/assets/d08d9ae5-0760-4bf1-ac7b-0a78f25c1d24)

## Checklist

- [x] Pull request attached to the appropriate user story in Azure DevOps
- [x] ADR decision log updated (if needed)
- [x] Release notes added to CHANGELOG.md
- [ ] Testing complete - all manual and automated tests pass

2024-10-24 14:40 UTC, DrizzlyOwl requested changes
The WAF rules will need to be adjusted to accommodate this change. I will update my review to approved once those changes are applied.

2024-10-24 15:19 UTC, DrizzlyOwl submitted a review, later dismissed

2024-10-25 08:21 UTC, dynamictulip commented on DfE.FindInformationAcademiesTrusts/Pages/Cookies.cshtml.cs
> +        var optionalCookiePrefixes = new[] { "ai_session", "ai_user", "ai_authUser" };
While we're renaming this cookie, shall we update it on the cookies table in the UI?

2024-10-25 08:24 UTC, dynamictulip approved these changes

2024-10-25 09:27 UTC, dynamictulip submitted a review, later dismissed

2024-10-25 10:18 UTC, DrizzlyOwl submitted a review, later dismissed

2024-10-28 10:31 UTC, dynamictulip approved these changes

2024-10-28 15:03 UTC, merged